name: 'ci'
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-latest' }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # Cypress Component Testing with Vite cannot run successfully
          # on Windows **CI** machines, due to resource restraints, this is a known issue.
          # So we'll just test it locally.
          # Later when Vitest becomes stable, we may switch to that for unit testing.
          # - windows-latest
        node-version:
          - 16
        include:
          - node-version: 14
            os: ubuntu-latest
          - node-version: 17
            os: ubuntu-latest
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm pretest
      # Rerun install to ensure the dependencies in the playground apps are resolved correctly
      - run: pnpm install
      - run: pnpm test
